FROM python:3.11-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY CHANGELOG.md ./
ARG VERSION=undefined
ENV VERSION=${VERSION}

COPY ./src ./src
COPY ./config ./config

CMD ["uv", "run", "python", "-m", "src.worker.cli"]
