"""add_gin_index_to_payload_metadata

Revision ID: 081d0b8d8cdb
Revises: f15d346a1391
Create Date: 2026-05-12 11:20:22.862659

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "081d0b8d8cdb"
down_revision: Union[str, Sequence[str], None] = "f15d346a1391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_embeddings_payload_metadata_gin",
        "embeddings",
        ["payload_metadata"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_embeddings_payload_metadata_gin", table_name="embeddings", postgresql_using="gin"
    )
    # ### end Alembic commands ###
