"""add_vector_purpose_metadata_and_hnsw

Revision ID: f15d346a1391
Revises: 8dd8f7f5288f
Create Date: 2026-04-03 12:04:49.737114

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f15d346a1391"
down_revision: Union[str, Sequence[str], None] = "8dd8f7f5288f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    op.execute("CREATE TYPE vector_purpose_enum AS ENUM ('IDENTITY', 'INTEREST', 'CONTENT')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "embeddings",
        sa.Column(
            "vector_purpose",
            sa.Enum("IDENTITY", "INTEREST", "CONTENT", name="vector_purpose_enum"),
            nullable=False,
        ),
    )
    op.add_column(
        "embeddings",
        sa.Column("payload_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###

    # Create HNSW index on vector_data
    op.execute("""
        CREATE INDEX ix_embeddings_vector_data_hnsw 
        ON embeddings 
        USING hnsw (vector_data vector_cosine_ops)
    """)


def downgrade() -> None:
    """Downgrade schema."""

    # Drop HNSW index
    op.execute("DROP INDEX IF EXISTS ix_embeddings_vector_data_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embeddings", "payload_metadata")
    op.drop_column("embeddings", "vector_purpose")
    # ### end Alembic commands ###

    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS vector_purpose_enum")
